SELECT COUNT(PRODUCTCODE), SELLERID
FROM supplychain
where AUDIT_MTH = 'Jan-16'
GROUP BY SELLERID;

--AVERAGE ORDER PRICE PER SELLER PER MONTH
SELECT AVG(Order_Price), SELLERID
FROM supplychain
WHERE AUDIT_MTH = 'Jan-16'
GROUP BY SELLERID
ORDER BY SELLERID ASC;

--AVERAGE ORDER PRICE PER CATEGORY PER SELLER PER MONTH
SELECT AVG(Order_Price), categoryname, SELLERID
FROM supplychain
WHERE AUDIT_MTH = 'Jan-16'
GROUP BY categoryname, SELLERID
ORDER BY SELLERID ASC;

--AVERAGE ORDER PRICE PER PRODUCT PER SELLER PER MONTH
SELECT AVG(Order_Price), PRODUCTCODE, SELLERID
FROM supplychain
WHERE AUDIT_MTH = 'Jan-16'
GROUP BY PRODUCTCODE, SELLERID
ORDER BY SELLERID ASC;

--AVERAGE ORDER PRICE PER BUYER PER MONTH
SELECT AVG(Order_Price), BUYERID
FROM supplychain
WHERE AUDIT_MTH = 'Jan-16'
GROUP BY BUYERID
ORDER BY BUYERID ASC;

--AVERAGE ORDER PRICE PER CATEGORY PER BUYER PER MONTH
SELECT AVG(Order_Price), categoryname, BUYERID
FROM supplychain
WHERE AUDIT_MTH = 'Jan-16'
GROUP BY categoryname, BUYERID
ORDER BY BUYERID ASC;

--AVERAGE ORDER PRICE PER PRODUCT PER BUYER PER MONTH
SELECT AVG(Order_Price), PRODUCTCODE, BUYERID
FROM supplychain
WHERE AUDIT_MTH = 'Jan-16'
GROUP BY PRODUCTCODE, BUYERID
ORDER BY BUYERID ASC;
