CREATE TABLE supplychain
(
  BUYERID INT,
  SELLERID INT,
  AUDIT_MTH VARCHAR(50),
  PRODUCTCODE INT,
  CATEGORYNAME VARCHAR(50),
  DISPLAY_DESCRIPTION	VARCHAR(250),
  Total_Qty INT,
  AvgPrice DECIMAL,
  Order_Price DECIMAL
);
